Repository FredHutch/wiki, pull requests merged in 2018-10, with the labels that each got.

#127 vs code settings changed
  .vscode/settings.json
  assets/screenshots/2018-09-27-11-22-50.png
Labels: SciComp

#114 Sgglick patch 2
  _generation/clsp_clinicalCov.md
Labels: generation

#117 economy file local
  _compdemos/EconomyCommand-API.md
  _compdemos/Mountain-CyberDuck.md
  _compdemos/synology.md
  _computing/store_objectstore.md
  assets/store_objectstore_swift/2018-09-25-11-25-43.png
  assets/store_objectstore_swift/2018-09-25-11-26-44.png
  assets/store_objectstore_swift/2018-09-25-11-27-27.png
Labels: SciComp

#137 add github pages theme repo demo page
  _infdemos/github_pages-FHtheme.md
Labels: bioinformatics

#136 Updating Git page in Bioinformatics section
  _bioinformatics/compute_github.md
Labels: bioinformatics

#134 Minor changes after team meeting
  _data/navigation.yml
Labels: SciComp

#144 Collaborative data storage: AWS S3 and OneDrive
  _compdemos/aws-R.md
  _compdemos/aws-cli.md
  _compdemos/aws-python.md
  _computing/store_collaboration.md
  _computing/store_objectstore.md
Labels: SciComp

#152 Quick r studio deduplication
  _bioinformatics/compute_uis.md
  _bioinformatics/prog_R.md
Labels: bioinformatics

#141 Adding information on data management options in beagle
  _infdemos/how_to_beagle.md
Labels: SciComp

#154 Formatting repair on access_credentials.md
  _computing/access_credentials.md
Labels: web-styling

#163 Make edit this page/comment link show up at top and bottom of pages
  _drafts/contentTemplate.md
  _includes/social-share.html
  _layouts/single.html
Labels: web-styling

#145 Caisis/HDC Data Request process
  _generation/clsp_clinicalCov.md
Labels: generation
