Repository FredHutch/wiki, pull requests merged in 2019-11, with the labels that each got.

#431 compdemos/github_pages-FHtheme/ - minor edits and corrections to text
  _compdemos/github_pages-FHtheme.md
Labels: new/edit content

#442 Fix link for howtoRhino page
  _scicomputing/compute_platforms.md
Labels: content repair

#454 refresh shiny!!!
  _compdemos/shiny.md
Labels: refresh content

#453 add explainshell
  _scicomputing/software_linux101.md
Labels: refresh content
