Repository FredHutch/wiki, pull requests merged in 2025-03, with the labels that each got.

#1161 Add announcement for maintenance
  _scicompannounce/2025-03-14-april-maintenance.md
Labels: scientific computing, new content

#1171 Update smoorthi.md
  _contributors/smoorthi.md
Labels: refresh content

#1172 Updates for scratch, working, and secure
  _scicomputing/store_objectstore.md
  _scicomputing/store_overview.md
  _scicomputing/store_posix.md
  _scicomputing/store_scratch.md
  _scicomputing/store_task.md
  _scicomputing/store_temp.md
  _scicomputing/store_working.md
Labels: content repair
